apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stocks-web

resources:
  - namespace.yaml
  - secrets.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: stocks-web
  app.kubernetes.io/managed-by: kustomize