apiVersion: v1
kind: Service
metadata:
  name: stocks-web-backend
  namespace: stocks-web
  labels:
    app: stocks-web-backend
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: stocks-web-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
