apiVersion: v1
kind: Service
metadata:
  name: stocks-web-frontend
  namespace: stocks-web
  labels:
    app: stocks-web-frontend
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: stocks-web-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
