apiVersion: v1
kind: Secret
metadata:
  name: stocks-web-secrets
  namespace: stocks-web
type: Opaque
stringData:
  DATABASE_URL: "postgres://stocks-admin:Ran0dal5!2706@10.36.0.12:5432/stocks-data?sslmode=require"
  JWT_SECRET: "WoWNVgfxXzIwSmUjxNY4ki5CJlseTf0W7xDk37V3KSY="
  REFRESH_SECRET: "QuUD7Njjsh5zpQTr+YqMAeocgY67TwzJlXsntG7OxNY="
  ADMIN_SECRET: "ToTheMoon!2026"
